import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const template = await readFile(join(root, "templates", "mcp-app.html"), "utf8");
const result = await build({
  entryPoints: [join(root, "src", "app.ts")],
  bundle: true,
  write: false,
  format: "iife",
  platform: "browser",
  target: ["es2022"],
  minify: true,
  legalComments: "none"
});
const bundle = result.outputFiles?.[0]?.text;
if (!bundle) throw new Error("dev console bundle was not produced");
const html = template.replace("/*__KODEGPT_APP_BUNDLE__*/", bundle);
const remoteAssetPatterns = [
  /(?:src|href)=["']https?:\/\//i,
  /url\(\s*["']?https?:\/\//i
];
if (remoteAssetPatterns.some((pattern) => pattern.test(html))) {
  throw new Error("dev console HTML must not contain remote asset references");
}
await writeFile(
  join(root, "src", "generated-html.ts"),
  `// Generated by scripts/build-app.mjs. Do not edit manually.\nexport const DEV_CONSOLE_HTML = ${JSON.stringify(html)};\n`
);
